### PR TITLE
update tomls to workaround version issues

### PR DESCRIPTION
**Pull request by rejuvyesh**
Tested that this works on `julia v1.3`. Should likely work on newer versions too.

### CODE REVIEW

**Comment by rejuvyesh** [comment]
With verbosity turned on as in the script:
```
[ Info: trim
(ulift[1])[end] = 4.64966422164289
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
1     0       50.5968668  3.48e+05 
    iter cost          expected    z         α         dJ        grad      zero_count ρ         info                                              
____----------------------------------------------------------------------------------------------------------------------------------------------
    2     100.74207027  347876.322  0.999929  1         3.48e+05  6.087234 0           0e+00    
    3     20.25083972   92.5318526  0.869876  1         80.49123  0.157311 0           0e+00    
    4     1.6776348839  19.5978678  0.947716  1         18.5732   0.058717 0           0e+00    
    5     0.0219767803  1.65999919  0.997385  1         1.655658  0.015063 0           0e+00    
    6     0.014083893   0.00789147  1.00018   1         0.007893  0.001196 0           0e+00    
    7     0.0140834992  3.9368e-07  1.000237  1         3.94e-07  7.52e-06 0           0e+00    
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
2     7       0.06983637  0.014083 
    iter cost          expected    z         α         dJ        grad      zero_count ρ         info                                              
____----------------------------------------------------------------------------------------------------------------------------------------------
    2     0.0142294747  5.1064e-06  1.001964  1         5.12e-06  2.55e-05 0           0e+00    
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
3     9       0.06691807  0.014229 
    iter cost          expected    z         α         dJ        grad      zero_count ρ         info                                              
____----------------------------------------------------------------------------------------------------------------------------------------------
    2     0.0152797786  0.00034976  1.002137  1         0.000351  0.000179 0           0e+00    
    3     0.0152797721  6.4822e-09  0.999679  1         6.48e-09  5.14e-07 0           0e+00    
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
4     12      0.0469306   0.01528  
    iter cost          expected    z         α         dJ        grad      zero_count ρ         info                                              
____----------------------------------------------------------------------------------------------------------------------------------------------
    2     0.0174127047  0.00525206  1.000924  1         0.005257  0.000415 0           0e+00    
    3     0.0174126677  3.6877e-08  1.003336  1         3.7e-08   9.69e-07 0           0e+00    
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
5     15      0.00929711  0.017413 
    iter cost          expected    z         α         dJ        grad      zero_count ρ         info                                              
____----------------------------------------------------------------------------------------------------------------------------------------------
    2     0.0178435407  0.00317898  1.000162  1         0.003179  0.000167 0           0e+00    
    3     0.0178435373  3.3117e-09  1.019713  1         3.38e-09  1.94e-07 0           0e+00    
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
6     18      0.00043938  0.017844 
(ulift[1])[end] = 4.64966422164289
```

It seems to me that the cost is _not_ going down as much in the AugLag step after the trim condition.
```
[ Info: auglag
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
1     0       5.99999957  5402.277 
    iter cost          expected    z         α         dJ        grad      zero_count ρ         info                                              
____----------------------------------------------------------------------------------------------------------------------------------------------
    2     3.3920285275  5399.52196  0.999882  1         5398.885  0.785962 0           0e+00    
    3     2.7684634322  0.63587982  0.980634  1         0.623565  0.011099 0           0e+00    
    4     2.7606820919  0.00871884  0.892474  1         0.007781  0.003836 0           0e+00    
    5     2.7602888438  0.00048595  0.809235  1         0.000393  0.001222 0           0e+00    
    6     2.7602590058  0.00004333  0.688672  1         2.98e-05  0.000465 0           0e+00    
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
2     6       1.34998614  2.760259 
    iter cost          expected    z         α         dJ        grad      zero_count ρ         info                                              
____----------------------------------------------------------------------------------------------------------------------------------------------
    2     2.7939438673  0.02416818  0.88041   1         0.021278  0.023379 0           0e+00    
    3     2.7927080085  0.00138031  0.895348  1         0.001236  0.001547 0           0e+00    
    4     2.7926520783  0.00007911  0.706965  1         5.59e-05  0.000557 0           0e+00    
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
3     10      0.92739513  2.792652 
    iter cost          expected    z         α         dJ        grad      zero_count ρ         info                                              
____----------------------------------------------------------------------------------------------------------------------------------------------
    2     2.8776444897  0.13174105  0.884033  1         0.116463  0.023089 0           0e+00    
    3     2.8646109081  0.01309017  0.995677  1         0.013034  0.00105  0           0e+00    
    4     2.864554529   0.0000652   0.864672  1         5.64e-05  0.000239 0           0e+00    
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
4     14      0.48790047  2.864555 
    iter cost          expected    z         α         dJ        grad      zero_count ρ         info                                              
____----------------------------------------------------------------------------------------------------------------------------------------------
    2     2.9268892502  0.19419734  0.990876  1         0.192425  0.01174  0           0e+00    
    3     2.9241726166  0.00270558  1.004087  1         0.002717  0.000382 0           0e+00    
    4     2.9241655369  6.3358e-06  1.117412  1         7.08e-06  5.14e-05 0           0e+00    
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
5     18      0.10036031  2.924166 
    iter cost          expected    z         α         dJ        grad      zero_count ρ         info                                              
____----------------------------------------------------------------------------------------------------------------------------------------------
    2     2.9369460773  0.0799519   1.000069  1         0.079957  0.003546 0           0e+00    
    3     2.9367762821  0.00017067  0.994886  1         0.00017   7.09e-05 0           0e+00    
    4     2.93677386    2.6054e-06  0.929662  1         2.42e-06  1.94e-05 0           0e+00    
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
6     22      0.00413293  2.936774 
    iter cost          expected    z         α         dJ        grad      zero_count ρ         info                                              
____----------------------------------------------------------------------------------------------------------------------------------------------
    2     2.9388234894  0.00703708  0.998788  1         0.007029  0.000507 0           0e+00    
    3     2.9388098341  0.00001372  0.995203  1         1.37e-05  2.3e-05  0           0e+00    
iter  total  c_max       cost      info                                              
-------------------------------------------------------------------------------------
7     25      0.00074591  2.93881  
```

**Comment by rejuvyesh** [comment]
@thowell It should now work on julia v1.6.

**Comment by thowell** [comment]
thanks for this fix!

**Comment by MAminSFV** [comment]
Thank you for the fix!

I am also wondering if I can make the models time-varying in this version? (Dependencies with RobotDynmaics, probably?)

**Pull request merged**
